package nodejs_test

// Test-only self-signed cert/key for TLS tests (generated once).
var testCertPEM = []byte(`-----BEGIN CERTIFICATE-----
MIIBWjCCAQCgAwIBAgIBATAKBggqhkjOPQQDAjAUMRIwEAYDVQQDEwlsb2NhbGhv
c3QwHhcNMjYwNzI0MDMxMTAwWhcNMzYwNzIxMDQxMTAwWjAUMRIwEAYDVQQDEwls
b2NhbGhvc3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS5B30VoncprgjMOtXE
qlWlcNCUJXRBk13a+EATCELWfMuHfj936XYcZi2OJna4RmNvO4FCY7ag/FwUGAxo
SrkPo0MwQTAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwEwGgYD
VR0RBBMwEYIJbG9jYWxob3N0hwR/AAABMAoGCCqGSM49BAMCA0gAMEUCIHhi6LKQ
ePaubxEPQ+rhXoWxkuN3+CMk+IhFJMsu8RCPAiEA2HZYekA3YvAZ/fS4Yu5wLILA
PMrEDqzFlP5uH4L+Muk=
-----END CERTIFICATE-----
`)

var testKeyPEM = []byte(`-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgFeK+T4wLYFPSeSS6
bYrtDcN5bfGsqWpho+/A1ydQtjehRANCAAS5B30VoncprgjMOtXEqlWlcNCUJXRB
k13a+EATCELWfMuHfj936XYcZi2OJna4RmNvO4FCY7ag/FwUGAxoSrkP
-----END PRIVATE KEY-----
`)
