#!/usr/bin/env bash
# babel-suite-deps.sh CHECKOUT OUTFILE
#
# Writes OUTFILE (a package.json) listing every published @babel/* package in
# the pinned checkout, at that checkout's own version. The fixture corpus names
# its plugins and presets the way Babel's config resolver expects
# ("transform-optional-chaining" -> @babel/plugin-transform-optional-chaining),
# so the whole set has to be installed for options.json to resolve — and it has
# to be the SAME version as the fixtures, or expected output drifts.
#
# Generating the list from the checkout instead of hand-maintaining ~150 entries
# is what keeps the two in step when the pin moves.
set -euo pipefail

checkout=$1
out=$2

if ! command -v jq >/dev/null; then
	echo "babel-suite-deps.sh needs jq" >&2
	exit 1
fi

deps=$(
	for pkg in "$checkout"/packages/*/package.json; do
		jq -r 'select((.private // false) | not)
		       | select(.name | startswith("@babel/"))
		       | select(.name | test("eslint|babel-cli|babel-node|standalone") | not)
		       | "\(.name)\t\(.version)"' "$pkg"
	done | sort -u | jq -Rn '[inputs | split("\t") | {(.[0]): .[1]}] | add'
)

cat >"$out" <<JSON
{
  "name": "babeltest-deps",
  "private": true,
  "description": "Generated by scripts/babel-suite-deps.sh — the @babel/* packages the pinned fixture corpus is run through. Do not edit.",
  "dependencies": $(echo "$deps" | jq -S .)
}
JSON
echo "==> wrote $out ($(echo "$deps" | jq 'length') packages)"
